//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WepFormFoad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eleve
    {
        public int IdEleve { get; set; }
        public string NomPrenomEleve { get; set; }
        public string EmailEleve { get; set; }
        public string AdresseEleve { get; set; }
        public int IdService { get; set; }
    }
}
